cmake_minimum_required(VERSION 3.0)

function(find_qt)
if(WIN32)
    set(qt_root "C:/Qt")
elseif(UNIX AND NOT APPLE)
    set(qt_root "$ENV{HOME}/Qt")
endif()

if (NOT DEFINED ARGV0)
    set(qt_version "")
    set(qt_root "${qt_root}")
else()
    if("${ARGV0}" MATCHES "^[0-9](\\.[0-9])*$")
        set(qt_version "${ARGV0}")
    endif()
    if("${ARGV0}" MATCHES "/" OR "${ARGV0}" MATCHES "\\\\" OR "${ARGV0}" MATCHES ":")
        message("${ARGV0}")
        set(qt_root "${ARGV0}")
    endif()
    if (DEFINED ARGV1)
        if("${ARGV1}" MATCHES "^[0-9](\\.[0-9])*$")
            set(qt_version "${ARGV1}")
        endif()
        if ("${ARGV1}" MATCHES "/" OR "${ARGV1}" MATCHES "\\\\" OR "${ARGV1}" MATCHES ":")
            message("${ARGV1}")
            set(qt_root "${ARGV1}")
        endif()
    else()
        if (NOT DEFINED qt_version)
            set(qt_version "")
        endif()
        if (NOT DEFINED qt_root)
            set(qt_root "${qt_root}")
        endif()
    endif()
endif()


if(DEFINED CMAKE_PREFIX_PATH)
    set(CMAKE_PREFIX_PATH_TEMP "${CMAKE_PREFIX_PATH}")
endif()

if(WIN32)
    set(qmake "bin/qmake.exe")
else()
    set(qmake "bin/qmake")
endif()

set(qt_cmake_dir "lib/cmake")

set(QT_FOUND OFF)

set(VER_REGEX "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$")

macro(__find_set_qt_version __path)
file(GLOB _children RELATIVE ${__path} ${__path}/*)
foreach(_child ${_children})
    if(EXISTS "${__path}/${_child}/${qt_cmake_dir}")
        set(qt_version ${child})
        break()
    endif()
endforeach()
endmacro()


if(NOT qt_version MATCHES ${VER_REGEX})
    file(GLOB children RELATIVE ${qt_root} ${qt_root}/*)
    list(REVERSE children)
    foreach(child ${children})
        if(IS_DIRECTORY ${qt_root}/${child})
            if("${child}" MATCHES "^${qt_version}" AND "${child}" MATCHES ${VER_REGEX})
                __find_set_qt_version("${qt_root}/${child}")
            elseif("${qt_version}" STREQUAL ""  AND "${child}" MATCHES ${VER_REGEX})
                __find_set_qt_version("${qt_root}/${child}")
            endif()
        endif()
    endforeach()
endif()


set(curdir ${qt_root}/${qt_version})


file(GLOB children RELATIVE ${curdir} ${curdir}/*)
set(dirlist "")
foreach(child ${children})
    if(IS_DIRECTORY ${curdir}/${child})
    list(APPEND dirlist ${child})
    endif()
endforeach()

foreach(subdir ${dirlist})
    if(${CMAKE_GENERATOR_PLATFORM} MATCHES "64")
        set(TARGET_ARCH "x64")
        if((EXISTS "${curdir}/${subdir}/${qt_cmake_dir}") AND ${subdir} MATCHES "64")
            set(CMAKE_PREFIX_PATH "${curdir}/${subdir}" PARENT_SCOPE)
            set(QT_FOUND ON)
        endif()
    elseif(${CMAKE_GENERATOR_PLATFORM} MATCHES "86" OR ${CMAKE_GENERATOR_PLATFORM} MATCHES "32")
    set(TARGET_ARCH "x86")
        if((EXISTS "${curdir}/${subdir}/${qt_cmake_dir}") AND NOT ${subdir} MATCHES "64")
            set(CMAKE_PREFIX_PATH "${curdir}/${subdir}" PARENT_SCOPE)
            set(QT_FOUND ON)
        endif()
    endif()
endforeach()

if(NOT ${QT_FOUND})
    message(SEND_ERROR  "No Qt(${TARGET_ARCH}) found at " ${curdir})
else()
    message("Qt(${TARGET_ARCH}) found at " ${curdir})
endif()

if(DEFINED CMAKE_PREFIX_PATH_TEMP)
    set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH_TEMP}" PARENT_SCOPE)
endif()

endfunction()
